# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Undone'), (2, 'Done')], default=1),
        ),
    ]
